# --------------------------------------------------- #
# Various execution environments for compiling code   #
# --------------------------------------------------- #

FROM node:16-alpine
WORKDIR /usr/golem